const mongoose = require("mongoose");

const property_schema = mongoose.Schema({
  user: { type: String, required: true },
  user_id: { type: String, required: true },
  ppd_id: { type: String, required: true },
  property_type: { type: String, required: true },
  contact: { type: Number, required: true },
  area: { type: Number, required: true },
  views: { type: Number, required: true },
  status: { type: String },
  days_left: { type: String },
  negotiable: { type: String },
  price: { type: Number, required: true },
  ownership: { type: String, required: true },
  property_age: { type: String, required: true },
  property_approved: { type: String },
  property_description: { type: String, required: true },
  bank_loan: { type: String, required: true },
  length: { type: String },
  breath: { type: String },
  total_area: { type: Number, required: true },
  area_unit: { type: String, required: true },
  no_of_bhk: { type: Number, required: true },
  no_of_floors: { type: Number, required: true },
  attached: { type: String },
  western: { type: String },
  furnished: { type: String, required: true },
  car_parking: { type: String },
  lift: { type: String },
  electricity: { type: String },
  facing: { type: String, required: true },
  owner_name: { type: String, required: true },
  mobile: { type: Number, required: true },
  postedby: { type: String },
  saletype: { type: String },
  featured_pkg: { type: String },
  ppd_pkg: { type: String },
  add_photo: { type: String },
  email: { type: String, required: true },
  city: { type: String, required: true },
  area_address: { type: String, required: true },
  landmark: { type: String, required: true },
  latitude: { type: String, required: true },
  longitude: { type: String, required: true },
});
const addNewProp = mongoose.model("Property", property_schema);
module.exports = { addNewProp };
